### PR TITLE
update to swift 3

### PR DESCRIPTION
**Pull request by dimohamdy**
update to swift 3

### CODE REVIEW

**Comment by dimohamdy** [comment]
@lypiut  please accept pull request

**Comment by lypiut** [comment]
Hi @dimohamdy

**Comment by lypiut** [comment]
Hi @dimohamdy

**Comment by lypiut** [comment]
Hi @dimohamdy 

Thank for you pull requests, I started the swift 3 port a long time ago but I never push the branch on Github.

I will check you PR

**Comment by lypiut** [comment]
Everything look good to me, thank for you work @dimohamdy  👍 😃

**Pull request merged**
