### PR TITLE
Update to Swift 5

### PR DESCRIPTION
**Pull request by dimohamdy**

### CODE REVIEW

**Comment by lypiut** [comment]
hello @dimohamdy thank for your pull request, I will check that quickly 😃

**Review by lypiut — APPROVED** [review]
Thank for your contribution, your PR look go to me 😄. Please rebase on the latest version of master. I fixed travis to run Xcode 10.3

**Comment by dimohamdy** [comment]
Check again Please

**Comment by lypiut** [comment]
@dimohamdy it's all good ! Don't forget to squash your commit before merging. I will push the update of cocoapods  when it's done

**Comment by dimohamdy** [comment]
Ok I will

**Pull request merged**
